# Generated by Django 3.0.10 on 2020-11-28 16:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
            ],
        ),
        migrations.CreateModel(
            name='CookCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='categories/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.CharField(max_length=500, verbose_name='Опис')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='films/', verbose_name='Фото')),
                ('publishDate', models.DateField(default=datetime.date.today, verbose_name='Дата опублікування')),
                ('isValid', models.BooleanField(default=False, verbose_name='Чи відповідає стандартам')),
                ('requiredTime', models.DurationField(blank=True, default=None, null=True, verbose_name='Тривалість приготування')),
                ('categories', models.ManyToManyField(blank=True, default=None, null=True, related_name='recipe_categories', to='reciper.Categories', verbose_name='Категорії')),
                ('cook_categories', models.ManyToManyField(blank=True, default=None, null=True, related_name='recipe_cook_categories', to='reciper.CookCategories', verbose_name='Категорії приготування')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=300, verbose_name='Опис')),
                ('order', models.PositiveSmallIntegerField(verbose_name='Порядок')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciper.Recipe', verbose_name='Рецепт')),
            ],
        ),
        migrations.CreateModel(
            name='ServiseUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='users/', verbose_name='Фото')),
                ('recipes', models.ManyToManyField(blank=True, default=None, null=True, related_name='user_saved', to='reciper.Recipe', verbose_name='Власні')),
                ('saved_recipes', models.ManyToManyField(blank=True, default=None, null=True, related_name='user_own', to='reciper.Recipe', verbose_name='Збережені рецепти')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Назва')),
                ('value', models.FloatField(verbose_name='Значення')),
                ('measure', models.CharField(max_length=50, verbose_name='Міра')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reciper.Recipe', verbose_name='Рецепт')),
            ],
        ),
    ]
