# Generated by Django 3.0.10 on 2020-12-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciper', '0002_auto_20201129_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='Кількість переглядів'),
        ),
        migrations.AlterField(
            model_name='serviseuser',
            name='recipes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='user_own', to='reciper.Recipe', verbose_name='Власні'),
        ),
        migrations.AlterField(
            model_name='serviseuser',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='user_saved', to='reciper.Recipe', verbose_name='Збережені рецепти'),
        ),
    ]
