# Generated by Django 3.0.10 on 2020-12-02 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reciper', '0003_auto_20201201_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviseuser',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='serviseuser',
            name='saved_recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_recipes', to='reciper.ServiseUser', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='severs',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='saved_recipes', to='reciper.ServiseUser', verbose_name='Зберегли'),
        ),
    ]
