# Generated by Django 3.0.10 on 2020-12-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciper', '0004_auto_20201203_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Опис'),
        ),
    ]
